### ISSUE TITLE
Possible to define function names for routes with decorator?

### ISSUE THREAD

**Issue by 128keaton** [nestjs/azure-func-http#108]
## I'm submitting a...

[X] Feature request
[X] Documentation issue or request

## Current behavior
The Azure Functions portal does not show any functions, it would be nice to have API routes here, for instance.
![functions](https://user-images.githubusercontent.com/1402918/73187009-51f6b580-40e6-11ea-8fff-be9b1d7c2290.PNG)

## Expected behavior
Have a decorator to mark controllers and methods or manually specify what should be defined, similar to how Swagger UI works.

## Environment
- Nest version: 6.1.1
- Node version: v12.14.1
- Platform:  Linux

**Comment by kamilmysliwiec** [comment]
This is something that we're planning as a part of this package https://github.com/nestjs/serverless-core
