### ISSUE TITLE
azure function + nest js + Graphql

### ISSUE THREAD

**Issue by aymen2323** [nestjs/azure-func-http#131]
use nest js graphql app in an azure function

The function is started, the submitted post is received in the function, but no response is sent to the client.

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue.

**Comment by aymen2323** [comment]
part1 - nest add 
@nestjs
/azure-func-http => npm run build && func host start ==> works fine :-)
part2 - https://github.com/nestjs/nest/tree/master/sample/23-type-graphql ==> works fine :-)
part3 - I try to merge accessing graphql through azure function ==> no way :-(
POST http://localhost:7071/api/graphql
is started (see logs) but no reponse is sent.
So,
no sample found on the internet :-(
here my config, if you can help me.
Thanks!

**Comment by kamilmysliwiec** [comment]
Can you please provide a minimal repository which reproduces your issue? So we can simply clone and have the same version locally.

**Comment by agmoss** [comment]
@aymen2323 I had the same problems as you and I worked out a fix. I have a small tutorial and repo at https://github.com/agmoss/nestjs-graphql-azure-functions I hope it helps!
