### ISSUE TITLE
Cronjobs support

### ISSUE THREAD

**Issue by johnykes** [nestjs/azure-func-http#1379]
## I'm submitting a...
[x] Bug report
OR
[x] Feature request

## Current behavior
Cronjobs not working when using Azure Functions `start:azure`, but working when using only `nest start`

## Expected behavior
Cronjobs working in both scenarios.

## Example
```
  import { Cron, CronExpression } from '@nestjs/schedule';

  @Cron(CronExpression.EVERY_SECOND)
  async myCronjob() {
    console.log('do something')
  }
```

For Tooling issues:
- Node version:18
- Platform:  Windows & Linux

Others:
Thank you for developing this <3

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
