### ISSUE TITLE
Socket.io not working

### ISSUE THREAD

**Issue by ahsanhabib23** [nestjs/azure-func-http#229]
## I'm submitting a...

<pre><code>
[ ] Bug report
</code></pre>

## Current behavior

I have an Ionic project and a NestJs project integrated with azure-func-http. I am also using socket.io to make realtime communication between them. But socket.io is not working. Its working with the default NestJs project but not with the azure-func-http.
When I run locally I face: 

> Access to XMLHttpRequest at 'http://localhost:7071/socket.io/?EIO=3&transport=polling&t=N6eYJqK' from origin 'http://localhost:8100' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

When I run with the deployed one(deployed to Azure function with service plan where Websocket is turned on) I face: 

> GET https://my-nestjs-deployed-url/socket.io/?EIO=3&transport=polling&t=N6eYhXI 404 (Not Found)

I have tried to add the path and many other solutions. Nothing is working.
 

## Expected behavior

Communication via socket.io should be working

## Minimal reproduction of the problem with instructions
Here are the repositories where you can reproduce the issue:
Frontend Ionic project: https://github.com/ahsanhabib23/ionic-azurefunction-socketio-testing
Backend NestJs project: https://github.com/ahsanhabib23/nestjs-azurefunction-socketio-testing 

## Environment

<pre><code>
Nest info:

[System Information]
OS Version     : macOS Catalina
NodeJS Version : v12.16.1
NPM Version    : 6.14.4 

[Nest CLI]
Nest CLI Version : 7.1.2 

[Nest Platform Information]
platform-socket.io version : 7.0.8
platform-express version   : 7.0.0
azure-func-http version    : 0.5.0
websockets version         : 7.0.8
common version             : 7.0.0
core version               : 7.0.0

Ionic Info:

Ionic:

   Ionic CLI                     : 6.6.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.0.7
   @angular-devkit/build-angular : 0.803.26
   @angular-devkit/schematics    : 8.3.26
   @angular/cli                  : 8.3.26
   @ionic/angular-toolkit        : 2.2.0

Utility:

   cordova-res (update available: 0.13.0) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   NodeJS : v12.16.1 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS Catalina

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
