### ISSUE TITLE
Using Multiple Azure function in one app

### ISSUE THREAD

**Issue by iliassays** [nestjs/azure-func-http#49]
Currently I can see one index.ts inside Main folder which has code like 
`export default function(context: Context, req: HttpRequest): void {
  AzureHttpAdapter.handle(createApp, context, req);
}`

If I have another azure function in same app, what is the recommended approach? See the below code which we have in .NetCore

`
public static class ClientInfoFuncion
    {
        [FunctionName("IP")]
        public static IActionResult GetClientIp(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("Requesting client IP.");
            var ip = req.HttpContext.Connection.RemoteIpAddress.ToString();
            return ip != null
                ? (ActionResult)new OkObjectResult($"{ip}")
                : new BadRequestObjectResult("ip is null");
        }

        [FunctionName("UserAgent")]
        public static IActionResult GetClientUserAgent(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("Requesting client User-Agent.");
            var ua = req.Headers["User-Agent"].ToString();
            return ua != null
                ? (ActionResult)new OkObjectResult($"{ua}")
                : new BadRequestObjectResult("user-agent is null");
        }
    }
`

**Comment by kamilmysliwiec** [comment]
For this, another package should be used (https://github.com/nestjs/azure-serverless). Docs are coming shortly

**Comment by iliassays** [comment]
Do you have any working example of how to use?

**Comment by kauandotnet** [comment]
> For this, another package should be used (https://github.com/nestjs/azure-serverless). Docs are coming shortly

@kamilmysliwiec, if you build more "complex" example, I can help with the documentation.
